version: '3.8'

services:
  db:
    image: postgres:15
    restart: always

    # Use variable substitution to load values from the .env file.
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    ports:
      # It's good practice in production to not expose the port directly to the host,
      # unless you specifically need external access. For inter-container communication,
      # no port mapping is needed. I'll leave it here for demonstration.
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    # A healthcheck tests that the container is not just running, but working.
    # This check ensures PostgreSQL is ready to accept connections.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local